# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{breadmachine}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Southerden"]
  s.date = %q{2009-10-31}
  s.description = %q{BreadMachine facilitates payment processing, including 3-D Secure, with the SecureTrading XPay gateway}
  s.email = %q{matt@localbubble.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    "lib/breadmachine.rb",
     "lib/breadmachine/dto/card.rb",
     "lib/breadmachine/dto/customer_info.rb",
     "lib/breadmachine/dto/order_info.rb",
     "lib/breadmachine/dto/three_d_secure_credentials.rb",
     "lib/breadmachine/extensions.rb",
     "lib/breadmachine/extensions/money.rb",
     "lib/breadmachine/extensions/string.rb",
     "lib/breadmachine/secure_trading.rb",
     "lib/breadmachine/secure_trading/auth_request.rb",
     "lib/breadmachine/secure_trading/auth_reversal_request.rb",
     "lib/breadmachine/secure_trading/auth_reversal_response.rb",
     "lib/breadmachine/secure_trading/card_xml.rb",
     "lib/breadmachine/secure_trading/config.rb",
     "lib/breadmachine/secure_trading/customer_info_auth_xml.rb",
     "lib/breadmachine/secure_trading/customer_info_enrolment_xml.rb",
     "lib/breadmachine/secure_trading/moto_auth_request.rb",
     "lib/breadmachine/secure_trading/order_info_xml.rb",
     "lib/breadmachine/secure_trading/payment_methods.rb",
     "lib/breadmachine/secure_trading/request.rb",
     "lib/breadmachine/secure_trading/st_3d_auth_request.rb",
     "lib/breadmachine/secure_trading/st_3d_auth_response.rb",
     "lib/breadmachine/secure_trading/st_3d_card_query_request.rb",
     "lib/breadmachine/secure_trading/st_3d_card_query_response.rb",
     "lib/breadmachine/secure_trading/three_d_secure_credentials_xml.rb",
     "lib/breadmachine/secure_trading/xpay.rb",
     "lib/breadmachine/secure_trading/xpay_response.rb",
     "lib/breadmachine/secure_trading/xpay_socket.rb"
  ]
  s.homepage = %q{http://github.com/mattsoutherden/breadmachine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{breadmachine}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Make dough with Bread Machine; a ruby library for payment processing.}
  s.test_files = [
    "spec/blueprints.rb",
     "spec/breadmachine_spec.rb",
     "spec/extensions/money_spec.rb",
     "spec/secure_trading/auth_request_spec.rb",
     "spec/secure_trading/bread_machine_spec.rb",
     "spec/secure_trading/card_xml_spec.rb",
     "spec/secure_trading/config_spec.rb",
     "spec/secure_trading/customer_info_auth_xml_spec.rb",
     "spec/secure_trading/customer_info_enrolment_xml_spec.rb",
     "spec/secure_trading/moto_auth_request_spec.rb",
     "spec/secure_trading/order_info_xml_spec.rb",
     "spec/secure_trading/request_spec.rb",
     "spec/secure_trading/st_3d_auth_request_spec.rb",
     "spec/secure_trading/st_3d_auth_response_spec.rb",
     "spec/secure_trading/st_3d_card_query_request_spec.rb",
     "spec/secure_trading/st_3d_card_query_response_spec.rb",
     "spec/secure_trading/st_auth_reversal_request_spec.rb",
     "spec/secure_trading/st_refund_request_spec.rb",
     "spec/secure_trading/st_refund_reversal_request_spec.rb",
     "spec/secure_trading/st_settlement_request_spec.rb",
     "spec/secure_trading/three_d_secure_credentials_xml_spec.rb",
     "spec/secure_trading/xpay_response_spec.rb",
     "spec/secure_trading/xpay_socket_spec.rb",
     "spec/secure_trading/xpay_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/matchers/have_tag.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<money>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<notahat-machinist>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rest-client>, [">= 0"])
    else
      s.add_dependency(%q<money>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<notahat-machinist>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
    end
  else
    s.add_dependency(%q<money>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<notahat-machinist>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
  end
end

